{% set name = "hdf5-otm" %}
{% set version = "1.14.2" %}
{% set maj_min_ver = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-{{ maj_min_ver }}/hdf5-{{ version }}/src/hdf5-{{ version }}.tar.gz
    sha256: 1c342e634008284a8c2794c8e7608e2eaf26d01d445fb3dfd7f33cb2fb51ac53

build:
  number: 0

requirements:
  build:
    - cmake
    - curl
    - m2w64-toolchain
    - m2w64-msmpi
  run:
    - m2w64-msmpi

about:
  home: https://www.hdfgroup.org/solutions/hdf5/
  license: LicenseRef-HDF5
  license_family: BSD
  license_file: COPYING
  summary: HDF5 is a data model, library, and file format for storing and managing data
  dev_url: https://github.com/HDFGroup/hdf5
  doc_url: https://portal.hdfgroup.org/display/HDF5/HDF5

extra:
  recipe-maintainers:
    - nicogodet